import { BoxInterface, CARD_TYPE } from '../interfaces';

export enum BASE_BOXES {
  BASE = 'AEONS_END_BASE',
  BASE2 = 'AEONS_END_BASE2',
}

export const AEONS_END_BASE: BoxInterface = {
  name: BASE_BOXES.BASE,
  cards: [
    {
      id: 1,
      name: 'Нефрит',
      value: 2,
      type: CARD_TYPE.GEM,
      collection: 'aeons_base',
    },
    {
      id: 2,
      name: 'Врисвудский янтарь',
      type: CARD_TYPE.GEM,
      value: 3,
      collection: 'aeons_base',
    },
    {
      id: 3,
      name: 'Очищающая жемчужина',
      type: CARD_TYPE.GEM,
      value: 3,
      collection: 'aeons_base',
    },
    {
      id: 4,
      name: 'Скопление алмазов',
      value: 4,
      type: CARD_TYPE.GEM,
      collection: 'aeons_base',
    },
    {
      id: 5,
      name: 'Жгучий рубин',
      value: 4,
      type: CARD_TYPE.GEM,
      collection: 'aeons_base',
    },
    {
      id: 6,
      name: 'Горящий опал',
      value: 5,
      type: CARD_TYPE.GEM,
      collection: 'aeons_base',
    },
    {
      id: 7,
      name: 'Дымчатый сапфир',
      value: 6,
      type: CARD_TYPE.GEM,
      collection: 'aeons_base',
    },
    {
      id: 8,
      name: 'Изменчивый кинжал',
      value: 2,
      type: CARD_TYPE.RELIC,
      collection: 'aeons_base',
    },
    {
      id: 9,
      name: 'Нестабильная призма',
      value: 3,
      type: CARD_TYPE.RELIC,
      collection: 'aeons_base',
    },
    {
      id: 10,
      name: 'Закупоренный вихрь',
      value: 3,
      type: CARD_TYPE.RELIC,
      collection: 'aeons_base',
    },
    {
      id: 11,
      name: 'Взрывной посох',
      value: 4,
      type: CARD_TYPE.RELIC,
      collection: 'aeons_base',
    },
    {
      id: 12,
      name: 'Шар концентрации',
      value: 4,
      type: CARD_TYPE.RELIC,
      collection: 'aeons_base',
    },
    {
      id: 13,
      name: 'Талисман мага',
      value: 5,
      type: CARD_TYPE.RELIC,
      collection: 'aeons_base',
    },

    {
      id: 14,
      name: 'Спектральное эхо',
      value: 3,
      type: CARD_TYPE.SPELL,
      collection: 'aeons_base',
    },
    {
      id: 15,
      name: 'Пламя феникса',
      value: 3,
      type: CARD_TYPE.SPELL,
      collection: 'aeons_base',
    },
    {
      id: 16,
      name: 'Лавовый узор',
      value: 4,
      type: CARD_TYPE.SPELL,
      collection: 'aeons_base',
    },
    {
      id: 17,
      name: 'Воспламенение',
      value: 4,
      type: CARD_TYPE.SPELL,
      collection: 'aeons_base',
    },
    {
      id: 18,
      name: 'Усиление видения',
      value: 4,
      type: CARD_TYPE.SPELL,
      collection: 'aeons_base',
    },
    {
      id: 19,
      name: 'Полёт забвения',
      value: 5,
      type: CARD_TYPE.SPELL,
      collection: 'aeons_base',
    },
    {
      id: 20,
      name: 'Тёмный огонь',
      value: 5,
      type: CARD_TYPE.SPELL,
      collection: 'aeons_base',
    },
    {
      id: 21,
      name: 'Хищная молния',
      value: 5,
      type: CARD_TYPE.SPELL,
      collection: 'aeons_base',
    },
    {
      id: 22,
      name: 'Кража духа',
      value: 5,
      type: CARD_TYPE.SPELL,
      collection: 'aeons_base',
    },

    {
      id: 23,
      name: 'Планарное озарение',
      value: 6,
      type: CARD_TYPE.SPELL,
      collection: 'aeons_base',
    },
    {
      id: 24,
      name: 'Дуга хаоса',
      value: 6,
      type: CARD_TYPE.SPELL,
      collection: 'aeons_base',
    },
    {
      id: 25,
      name: 'Огненный хлыст',
      value: 6,
      type: CARD_TYPE.SPELL,
      collection: 'aeons_base',
    },
    {
      id: 26,
      name: 'Мистические узы',
      value: 7,
      type: CARD_TYPE.SPELL,
      collection: 'aeons_base',
    },
    {
      id: 27,
      name: 'Поглощающая пустота',
      value: 7,
      type: CARD_TYPE.SPELL,
      collection: 'aeons_base',
    },
  ],
};
